{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2014-10077",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/rubysec/ruby-advisory-db/pull/182/files",
          "name": "https://github.com/rubysec/ruby-advisory-db/pull/182/files",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/svenfuchs/i18n/pull/289",
          "name": "https://github.com/svenfuchs/i18n/pull/289",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/svenfuchs/i18n/releases/tag/v0.8.0",
          "name": "https://github.com/svenfuchs/i18n/releases/tag/v0.8.0",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2018/11/msg00021.html",
          "name": "[debian-lts-announce] 20181121 [SECURITY] [DLA 1584-1] ruby-i18n security update",
          "refsource": "MLIST",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Hash#slice in lib/i18n/core_ext/hash.rb in the i18n gem before 0.8.0 for Ruby allows remote attackers to cause a denial of service (application crash) via a call in a situation where :some_key is present in keep_keys but not present in the hash."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-11-06T15:29Z",
  "lastModifiedDate": "2018-11-22T11:29Z"
}