{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-18281",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugreports.qt.io/browse/QTBUG-77819",
          "name": "https://bugreports.qt.io/browse/QTBUG-77819",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1848784",
          "name": "https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1848784",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://codereview.qt-project.org/c/qt/qtbase/+/271889",
          "name": "https://codereview.qt-project.org/c/qt/qtbase/+/271889",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An out-of-bounds memory access in the generateDirectionalRuns() function in qtextengine.cpp in Qt qtbase 5.11.x and 5.12.x before 5.12.5 allows attackers to cause a denial of service by crashing an application via a text file containing many directional characters."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-10-23T15:15Z",
  "lastModifiedDate": "2019-10-23T15:15Z"
}