{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-10874",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.securitytracker.com/id/1041396",
          "name": "1041396",
          "refsource": "SECTRACK",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2150",
          "name": "RHSA-2018:2150",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2151",
          "name": "RHSA-2018:2151",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2152",
          "name": "RHSA-2018:2152",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2166",
          "name": "RHSA-2018:2166",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2321",
          "name": "RHSA-2018:2321",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2585",
          "name": "RHSA-2018:2585",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10874",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10874",
          "refsource": "CONFIRM",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In ansible it was found that inventory variables are loaded from current working directory when running ad-hoc command which are under attacker's control, allowing to run arbitrary code as a result."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-07-02T13:29Z",
  "lastModifiedDate": "2018-08-30T10:29Z"
}